openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: This is a sample API
servers:
  - url: http://localhost:8090
paths:
  /patient:
    get:
      summary: Returns a list of patients
      responses:
        200:
          description: A list of patients
    post:
      summary: Adds a new patient
      requestBody:
        description: The patient to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        200:
          description: The added patient
    put:
      summary: Updates an existing patient
      parameters:
        - name: id
          in: path
          description: The ID of the patient to update
          required: true
          schema:
            type: integer
      requestBody:
        description: The patient to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        200:
          description: The updated patient
    delete:
      summary: Deletes an existing patient
      parameters:
        - name: id
          in: path
          description: The ID of the patient to delete
          required: true
          schema:
            type: integer
      responses:
        200:
          description: The deleted patient
components:
  schemas:
    Patient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer
